# server settings
server:
  port: 8088

# logging settings
logging:
  level:
    com.npaw: DEBUG

# service settings
pluginDataService:
  clientConfigs:
  - accountCode: "clientA"
    targetDevice: "XBox"
    pluginVersion: "3.3.1"
    pingTime: 10
    hosts:
    - name: "clusterA.com"
      load: 70
    - name: "clusterB.com"
      load: 30
  - accountCode: "clientA"
    targetDevice: "Panasonic"
    pluginVersion: "3.3.2"
    pingTime: 5
    hosts:
    - name: "clusterB.com"
      load: 100
  - accountCode: "clientB"
    targetDevice: "osmf"
    pluginVersion: "3.3.1"
    pingTime: 5
    hosts:
    - name: "clusterA.com"
      load: 50
    - name: "clusterB.com"
      load: 50

