# server settings
server:
  port: 80

# logging settings
logging:
  level:
    com.npaw: DEBUG

pluginDataService:
  bizzThreadPoolConfig:
    corePoolSize: 8
    maxPoolSize: 16
    keepAliveTime: 60
  clientsConfigs:
    clientA:
      - targetDevice: "XBox"
        pluginVersion: "3.3.1"
        pingTime: 10
        hostsConfig:
        - name: "clusterA.com"
          load: 70
        - name: "clusterB.com"
          load: 30
      - targetDevice: "Panasonic"
        pluginVersion: "3.3.2"
        pingTime: 5
        hostsConfig:
        - name: "clusterB.com"
          load: 100
    clientB:
      - targetDevice: "osmf"
        pluginVersion: "3.3.1"
        pingTime: 5
        hostsConfig:
        - name: "clusterA.com"
          load: 50
        - name: "clusterB.com"
          load: 50